# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json


###
GET 127.0.0.1:8000/users/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXRuYXphcjA0IiwiZXhwIjoxNzQzNDQ0NDI5fQ.BemVEaTeDG0GKq7kRAh8k_Ci0Pyjacj5oB1YseGtLbs


### Login to get token (form)

POST http://127.0.0.1:8000/auth/login-form
Accept: application/json
Content-Type: application/x-www-form-urlencoded

username=Matnazar04&password=20040730python


### Login to get token


POST http://127.0.0.1:8000/auth/login-json
Accept: application/json
Content-Type: application/json

{
    "username": "Matnazar04",
    "password": "20040730python"
}


### Create new post with images
POST http://127.0.0.1:8000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXRuYXphcjA0IiwiZXhwIjoxNzQ4ODQ3NDkxfQ.mHZe-KbD364sb4boVmCmZGqcA4l4aIAet6BBFXEgKpQ
Content-Type: multipart/form-data; boundary=boundary
User-Agent: IntelliJ HTTP Client/PyCharm 2024.3.3
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

--boundary
Content-Disposition: form-data; name="name"

My First Post
--boundary
Content-Disposition: form-data; name="title"

This is a test post
--boundary
Content-Disposition: form-data; name="text"

This is the content of my first post. Hello World!
--boundary
Content-Disposition: form-data; name="images"; filename="test_image1.png"
Content-Type: image/png

< ./test_images/test_image1.png
--boundary
Content-Disposition: form-data; name="images"; filename="test_image2.png"
Content-Type: image/png

< ./test_images/test_image2.png
--boundary--

### Create new post without images
POST http://127.0.0.1:8000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXRuYXphcjA0IiwiZXhwIjoxNzQ4ODQ3NDkxfQ.mHZe-KbD364sb4boVmCmZGqcA4l4aIAet6BBFXEgKpQ
Content-Type: multipart/form-data; boundary=boundary
Accept: */*

--boundary
Content-Disposition: form-data; name="name"

My Second Post
--boundary
Content-Disposition: form-data; name="title"

Another test post
--boundary
Content-Disposition: form-data; name="text"

This is a simple post without images.
--boundary--

### Get a specific post id
GET http://127.0.0.1:8000/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXRuYXphcjA0IiwiZXhwIjoxNzQzNTM2NDk0fQ.2iGAh6Yr_0efzxFqbGEIUGPTiMnQYB7XmZvqWTE95ek
Accept: application/json

### Get all posts
GET http://127.0.0.1:8000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXRuYXphcjA0IiwiZXhwIjoxNzQzNTkyNjc0fQ.49RI7dcoCfu_0YUyVI1LK9pNr0sdsBgxiamgsg-RD9I
Accept: application/json

### Get an image (replace {image_path} with actual path from response, e.g., uploads/UUID_test_image1.png)
GET http://127.0.0.1:8000/images/{image_path}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXRuYXphcjA0IiwiZXhwIjoxNzQzNDQxMzQzfQ.Fg7aH3_KKzBDiXBHfPW2H-iCwJ7_5lDXJPni2AQBWGc
Accept: image/png





### Create new post with images
POST http://127.0.0.1:8000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJNYXRuYXphcjA0IiwiZXhwIjoxNzQzNTAxMjg4fQ.b7DCz2ud4N7gKkVbBrhEKVA40Z7SeQj5BbVNST81MDI
Content-Type: multipart/form-data; boundary=boundary
User-Agent: IntelliJ HTTP Client/PyCharm
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

--boundary
Content-Disposition: form-data; name="name"

My First Post
--boundary
Content-Disposition: form-data; name="title"

This is a test post
--boundary
Content-Disposition: form-data; name="text"

This is the content of my first post. Hello World!
--boundary
Content-Disposition: form-data; name="images"; filename="test_image1.png"
Content-Type: image/png

< ./test_images/test_image1.png
--boundary
Content-Disposition: form-data; name="images"; filename="test_image2.png"
Content-Type: image/png

< ./test_images/test_image2.png
--boundary--